# Generated by Django 4.1.4 on 2023-01-02 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                ("nickname", models.CharField(default="", max_length=100, unique=True)),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Seoul", "서울특별시"),
                            ("Busan", "부산광역시"),
                            ("Daegu", "대구광역시"),
                            ("Incheon", "인천광역시"),
                            ("Gwangju", "광주광역시"),
                            ("Daejeon", "대전광역시"),
                            ("Ulsan", "울산광역시"),
                            ("Sejong", "세종특별자치시"),
                            ("Gyeonggi", "경기도"),
                            ("Gwangwon", "강원도"),
                            ("Chungcheong_north", "충청북도"),
                            ("Chungcheong_south", "충청남도"),
                            ("Jeolla_north", "전라북도"),
                            ("Jeolla_south", "전라남도"),
                            ("Gyeongsang_north", "경상북도"),
                            ("Gyeongsang_south", "경상남도"),
                            ("Jeju", "제주도"),
                        ],
                        default="서울특별시",
                        max_length=100,
                    ),
                ),
                ("area", models.IntegerField(default=0)),
                (
                    "phone",
                    models.CharField(
                        default="",
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^01([0|1|6|7|8|9]?)([0-9]{3,4})([0-9]{4})$"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
