# Generated by Django 4.1.4 on 2022-12-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_remove_user_date_joined_and_more"),
        ("accounts", "0005_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = []
