# Generated by Django 4.1 on 2023-01-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user", name="area", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(
                choices=[
                    ("Seoul", "서울특별시"),
                    ("Busan", "부산광역시"),
                    ("Daegu", "대구광역시"),
                    ("Incheon", "인천광역시"),
                    ("Gwangju", "광주광역시"),
                    ("Daejeon", "대전광역시"),
                    ("Ulsan", "울산광역시"),
                    ("Sejong", "세종특별자치시"),
                    ("Gyeonggi", "경기도"),
                    ("Gwangwon", "강원도"),
                    ("Chungcheong_north", "충청북도"),
                    ("Chungcheong_south", "충청남도"),
                    ("Jeolla_north", "전라북도"),
                    ("Jeolla_south", "전라남도"),
                    ("Gyeongsang_north", "경상북도"),
                    ("Gyeongsang_south", "경상남도"),
                    ("Jeju", "제주도"),
                ],
                default="서울특별시",
                max_length=100,
                unique=True,
            ),
        ),
    ]
