# Generated by Django 4.1.4 on 2022-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="area",
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
