# Generated by Django 4.1.4 on 2022-12-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(
                choices=[
                    ("서울", "서울"),
                    ("경기", "경기"),
                    ("인천", "인천"),
                    ("강원", "강원"),
                    ("충북", "충북"),
                    ("충남", "충남"),
                    ("대전", "대전"),
                    ("세종", "세종"),
                    ("전북", "전북"),
                    ("전남", "전남"),
                    ("광주", "광주"),
                    ("대구", "대구"),
                    ("경북", "경북"),
                    ("경남", "경남"),
                    ("부산", "부산"),
                    ("울산", "울산"),
                    ("제주", "제주"),
                    ("해외", "해외"),
                ],
                default="서울",
                max_length=100,
                unique=True,
            ),
        ),
    ]
