# Generated by Django 4.1.4 on 2023-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="baechoo_new",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(max_length=20)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("avr", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("min", models.FloatField(blank=True, null=True)),
                ("rain", models.FloatField(blank=True, null=True)),
                ("sun", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
