# Generated by Django 4.1 on 2023-01-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("save_csv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="baechoo_new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(max_length=20)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("avr", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("min", models.FloatField(blank=True, null=True)),
                ("rain", models.FloatField(blank=True, null=True)),
                ("sun", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="inform_baechoo",),
    ]
