# Generated by Django 4.1.4 on 2023-01-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("save_csv", "0002_baechoo_new"),
    ]

    operations = [
        migrations.DeleteModel(
            name="inform_baechoo",
        ),
    ]
