# Generated by Django 4.1.4 on 2023-01-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("save_csv", "0003_delete_inform_baechoo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baechoo_new",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
