# Generated by Django 4.1.4 on 2023-01-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("save_csv", "0004_alter_baechoo_new_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baechoo_new",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
