import pandas as pd
import sqlite3

# Read csv file.
df = pd.read_csv("rawdata/진혁_데이터프레임.csv")

# Connect to (create) database.
database = "db.sqlite3"
conn = sqlite3.connect(database)
dtype={
    "지역" : "CharField",
    "계절" : "CharField",
    "연도" : "IntegerField",
    "평균기온(°C)_1월" : "FloatField",
    "최고기온(°C)_1월" : "FloatField",
    "최저기온(°C)_1월" : "FloatField",
    "월합강수량(00~24h만)(mm)_1월" : "FloatField",
    "합계 일사량(MJ/m2)_1월" : "FloatField",
    "평균기온(°C)_2월" : "FloatField",
    "최고기온(°C)_2월" : "FloatField",
    "최저기온(°C)_2월" : "FloatField",
    "월합강수량(00~24h만)(mm)_2월" : "FloatField",
    "합계 일사량(MJ/m2)_2월" : "FloatField",
    "평균기온(°C)_3월" : "FloatField",
    "최고기온(°C)_3월" : "FloatField",
    "최저기온(°C)_3월" : "FloatField",
    "월합강수량(00~34h만)(mm)_3월" : "FloatField",
    "합계 일사량(MJ/m3)_3월" : "FloatField",
    "평균기온(°C)_4월" : "FloatField",
    "최고기온(°C)_4월" : "FloatField",
    "최저기온(°C)_4월" : "FloatField",
    "월합강수량(00~44h만)(mm)_4월" : "FloatField",
    "합계 일사량(MJ/m4)_4월" : "FloatField",
    "평균기온(°C)_5월" : "FloatField",
    "최고기온(°C)_5월" : "FloatField",
    "최저기온(°C)_5월" : "FloatField",
    "월합강수량(00~55h만)(mm)_5월" : "FloatField",
    "합계 일사량(MJ/m5)_5월" : "FloatField",
    "평균기온(°C)_6월" : "FloatField",
    "최고기온(°C)_6월" : "FloatField",
    "최저기온(°C)_6월" : "FloatField",
    "월합강수량(00~66h만)(mm)_6월" : "FloatField",
    "합계 일사량(MJ/m6)_6월" : "FloatField",
    "평균기온(°C)_7월" : "FloatField",
    "최고기온(°C)_7월" : "FloatField",
    "최저기온(°C)_7월" : "FloatField",
    "월합강수량(00~77h만)(mm)_7월" : "FloatField",
    "합계 일사량(MJ/m7)_7월" : "FloatField",
    "평균기온(°C)_8월" : "FloatField",
    "최고기온(°C)_8월" : "FloatField",
    "최저기온(°C)_8월" : "FloatField",
    "월합강수량(00~88h만)(mm)_8월" : "FloatField",
    "합계 일사량(MJ/m8)_8월" : "FloatField",
    "평균기온(°C)_9월" : "FloatField",
    "최고기온(°C)_9월" : "FloatField",
    "최저기온(°C)_9월" : "FloatField",
    "월합강수량(00~99h만)(mm)_9월" : "FloatField",
    "합계 일사량(MJ/m9)_9월" : "FloatField",
    "평균기온(°C)_10월" : "FloatField",
    "최고기온(°C)_10월" : "FloatField",
    "최저기온(°C)_10월" : "FloatField",
    "월합강수량(00~1010h만)(mm)_10월" : "FloatField",
    "합계 일사량(MJ/m10)_10월" : "FloatField",
    "평균기온(°C)_11월" : "FloatField",
    "최고기온(°C)_11월" : "FloatField",
    "최저기온(°C)_11월" : "FloatField",
    "월합강수량(00~1111h만)(mm)_11월" : "FloatField",
    "합계 일사량(MJ/m11)_11월" : "FloatField",
    "평균기온(°C)_12월" : "FloatField",
    "최고기온(°C)_12월" : "FloatField",
    "최저기온(°C)_12월" : "FloatField",
    "월합강수량(00~1212h만)(mm)_12월" : "FloatField",
    "합계 일사량(MJ/m12)_12월" : "FloatField",
    "면적 (ha)" : "IntegerField",
    "생산량 (톤)" : "FloatField",
}
df.to_sql(name='save_csv_inform_baechoo', con=conn, if_exists='replace', dtype=dtype, index=True, index_label="id")  # dataframe을 sqlite로 저장
conn.close()