# Generated by Django 4.1.4 on 2023-01-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionMade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avr1", models.FloatField()),
                ("max1", models.FloatField()),
                ("min1", models.FloatField()),
                ("rain1", models.FloatField()),
                ("sun1", models.FloatField()),
                ("avr2", models.FloatField()),
                ("max2", models.FloatField()),
                ("min2", models.FloatField()),
                ("rain2", models.FloatField()),
                ("sun2", models.FloatField()),
                ("avr3", models.FloatField()),
                ("max3", models.FloatField()),
                ("min3", models.FloatField()),
                ("rain3", models.FloatField()),
                ("sun3", models.FloatField()),
            ],
        ),
    ]
