# Generated by Django 4.1.4 on 2023-01-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictioninput",
            name="month",
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
