# Generated by Django 4.1.4 on 2023-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0002_alter_predictioninput_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictioninput",
            name="month",
            field=models.DateField(max_length=20, null=True),
        ),
    ]
