# Generated by Django 4.1.4 on 2023-01-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "user info", "verbose_name_plural": "user infos"},
        ),
    ]
