# Generated by Django 4.1.4 on 2023-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_userinfo_id_alter_userinfo_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="area",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="location",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
