# Generated by Django 4.1.4 on 2023-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_userinfo_options_alter_userinfo_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="month",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
