# Generated by Django 4.1 on 2023-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_userinfo_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo", name="month", field=models.IntegerField(null=True),
        ),
    ]
