# Generated by Django 4.1.4 on 2023-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_userinfo_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="month",
            field=models.IntegerField(null=True),
        ),
    ]
