<<<<<<< Updated upstream
# Generated by Django 4.1.4 on 2023-01-12 01:14
=======
# Generated by Django 4.1.4 on 2023-01-12 15:45
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Predictiprice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.IntegerField()),
            ],
        ),
    ]
