# Generated by Django 4.1.4 on 2023-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("output", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionoutput", name="area", field=models.IntegerField(),
        ),
    ]
