<<<<<<< Updated upstream
# Generated by Django 4.1.4 on 2023-01-12 01:14
=======
# Generated by Django 4.1.4 on 2023-01-12 15:45
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("tm", models.IntegerField(default=0)),
                ("item_5", models.TextField()),
                ("item_20", models.TextField()),
                ("item_365", models.TextField()),
                ("area", models.IntegerField(default=0)),
                ("pred_1", models.IntegerField()),
                ("pred_2", models.IntegerField()),
                ("pred_3", models.IntegerField()),
                ("pred_4", models.IntegerField()),
                ("pred_5", models.IntegerField()),
                ("pred_10", models.IntegerField()),
                ("pred_20", models.IntegerField()),
                ("pred_60", models.IntegerField()),
                ("pred_120", models.IntegerField()),
            ],
        ),
    ]
